#!/usr/bin/env bash
#
# usage: ./all-owners.sh
#
# Generates ALL-OWNERS file with all Metal3 maintainers by cross-referencing:
# - OWNERS and OWNERS_ALIASES files from all Metal3 repos
# - CNCF project-maintainers.csv (name/company)
# - GitHub API (fallback for missing CNCF data)
# - Git commit history (email addresses)
#
# Existing emails in ALL-OWNERS are preserved.
#

set -eu

REPOS=(
    baremetal-operator
    cluster-api-provider-metal3
    community
    ip-address-manager
    ironic-hardware-inventory-recorder-image
    ironic-image
    ironic-ipa-downloader
    ironic-standalone-operator
    mariadb-image
    metal3-dev-env
    metal3-docs
    metal3-io.github.io
    project-infra
    utility-images
)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXISTING_OWNERS=""
WORKDIR=""

check_dependencies()
{
    command -v yq &>/dev/null || { echo >&2 "fatal: yq not found"; exit 1; }
    command -v jq &>/dev/null || { echo >&2 "fatal: jq not found"; exit 1; }
}

setup_workdir()
{
    WORKDIR=$(mktemp -d)
    trap 'rm -rf "${WORKDIR}"' EXIT

    # Copy existing ALL-OWNERS before potential truncation
    if [[ -f "${SCRIPT_DIR}/ALL-OWNERS" ]]; then
        cp "${SCRIPT_DIR}/ALL-OWNERS" "${WORKDIR}/existing-owners.txt"
        EXISTING_OWNERS="${WORKDIR}/existing-owners.txt"
    fi

    cd "${WORKDIR}"

    curl -s "https://raw.githubusercontent.com/cncf/foundation/main/project-maintainers.csv" > cncf.csv

    for repo in "${REPOS[@]}"; do
        git clone --quiet --bare "https://github.com/metal3-io/${repo}"
    done
}

get_approvers_from_repo()
{
    local repo="$1" filter alias_key

    if [[ "${repo}" = "metal3-io.github.io" ]]; then
        filter='.filters.".*".approvers'
        alias_key="metal3-io-github-io-maintainers"
    else
        filter='.approvers'
        alias_key="${repo}-maintainers"
    fi

    {
        git -C "${repo}.git" show "HEAD:OWNERS" 2>/dev/null | yq "${filter}" 2>/dev/null
        git -C "${repo}.git" show "HEAD:OWNERS_ALIASES" 2>/dev/null | yq ".aliases.${alias_key}" 2>/dev/null
    } | grep -vE "null|\.\.\.|maintainers" | sed 's/^- //'
}

get_maintainers_with_repos()
{
    declare -A maintainer_repos

    for repo in "${REPOS[@]}"; do
        while IFS= read -r handle; do
            [[ -z "${handle}" ]] && continue
            maintainer_repos[${handle}]+="${maintainer_repos[${handle}]:+,}${repo}"
        done < <(get_approvers_from_repo "${repo}")
    done

    for handle in $(printf '%s\n' "${!maintainer_repos[@]}" | sort -f); do
        echo "${handle}:${maintainer_repos[${handle}]}"
    done
}

lookup_in_cncf()
{
    local handle="$1"
    # Extract name, company, and GitHub handle from CNCF project-maintainers.csv
    # CSV format: Full Name,Project,Name,Company,GitHub Handle,Email
    # We extract fields 3,4,5 (Name,Company,GitHub Handle) matching on field 5
    sed -n '/,metal3-io,/,/^[^,]*,[^,][^,]*,/{ /,metal3-io,/p; /^,,/p; }' cncf.csv | \
        awk -F',' -v gh="${handle}" '$5 == gh {print $3","$4","$5}' | tr -d '\r'
}

lookup_in_github()
{
    local handle="$1" info name company

    info=$(curl -s "https://api.github.com/users/${handle}")
    name=$(echo "${info}" | jq -r '.name // empty')
    [[ -z "${name}" ]] && return 1

    company=$(echo "${info}" | jq -r '.company // empty' | sed 's/^@//')
    case "${company,,}" in
        ericsson) company="Ericsson Software Technology" ;;
        "red hat"|redhat) company="Red Hat" ;;
    esac

    echo "${name},${company},${handle}"
}

lookup_email()
{
    local handle="$1" name="$2" repos="$3"

    # Check existing file first
    if [[ -n "${EXISTING_OWNERS}" ]]; then
        local existing
        existing=$(grep ",${handle}," "${EXISTING_OWNERS}" 2>/dev/null | sed 's/.*,\([^,]*\)$/\1/' | grep -v "^$" | head -1)
        [[ -n "${existing}" ]] && { echo "${existing}"; return; }
    fi

    # Search git by author name in approver repos first
    local -a search_repos
    IFS=',' read -ra search_repos <<< "${repos}"
    for search in "${name}" "${name%% *}"; do
        for repo in "${search_repos[@]}"; do
            local mail
            mail=$(git -C "${repo}.git" log -i --author="${search}" -n 1 --format="%ae" 2>/dev/null)
            [[ -n "${mail}" ]] && { echo "${mail}"; return; }
        done
    done
}

get_maintainer_info()
{
    local handle="$1" repos="$2" info name email

    info=$(lookup_in_cncf "${handle}")
    [[ -z "${info}" ]] && info=$(lookup_in_github "${handle}")
    if [[ -z "${info}" ]]; then
        echo "- ${handle},----UNKNOWN_AFFILIATION-----"
        return
    fi

    name="${info%%,*}"
    email=$(lookup_email "${handle}" "${name}" "${repos}")
    echo "- ${info},${email}"
}

# Main
check_dependencies
setup_workdir

{
    cat <<'EOF'
# All approvers from all top-level OWNERS files, including OWNERS_ALIASES
# Generated by community/maintainers/all-owners.sh
# Each line represents an individual maintainer and the line has to
# contain the name, affiliation, GitHub handle and the e-mail of the
# maintainer.

approvers:
EOF
    mapfile -t maintainer_list < <(get_maintainers_with_repos)
    for entry in "${maintainer_list[@]}"; do
        get_maintainer_info "${entry%%:*}" "${entry#*:}"
    done
} > "${WORKDIR}/new-owners.txt"

cp "${WORKDIR}/new-owners.txt" "${SCRIPT_DIR}/ALL-OWNERS"
echo >&2 "Updated ${SCRIPT_DIR}/ALL-OWNERS"
