#!/usr/bin/env bash
#
# usage: ./all-owners.sh > ALL-OWNERS
#

set -eu

# repos and which branch is the default
declare -a REPOS=(
    baremetal-operator
    cluster-api-provider-metal3
    community
    ip-address-manager
    ironic-client
    ironic-hardware-inventory-recorder-image
    ironic-image
    ironic-ipa-downloader
    ironic-standalone-operator
    mariadb-image
    metal3-dev-env
    metal3-docs
    metal3-io.github.io
    project-infra
    utility-images
)

declare -a OWNER_TYPES=(
    approvers
)

declare -a CURL_OPTS=(
    --silent
)

# check dependencies are in place - yq is not commonly available
# as os package, and yq from Ubuntu snap is incompatible
INSTALL_URL="https://github.com/mikefarah/yq/issues/488"
command -v yq &>/dev/null || { echo >&2 "fatal: yq not found: see ${INSTALL_URL}"; exit 1; }

all_owners_raw()
{
    local owner_type maintainer_group filter

    owner_type="$1"

    for repo in "${REPOS[@]}"; do
        if [[ "${repo}" = "metal3-io.github.io" ]]; then
            filter=".filters.\".*\".${owner_type}"
            maintainer_group="metal3-io-github-io-maintainers"
        else
            filter=".${owner_type}"
            maintainer_group="${repo}-maintainers"
        fi

        branch=$(git remote show "https://github.com/metal3-io/${repo}" | sed -n '/HEAD branch/s/.*: //p')

        # NOTE: yq -y is not supported by any recent version of yq
        # get direct approvers
        curl "${CURL_OPTS[@]}" \
            "https://raw.githubusercontent.com/metal3-io/${repo}/${branch}/OWNERS" | \
            yq "${filter}"
        # get approvers via alias
        curl "${CURL_OPTS[@]}" \
            "https://raw.githubusercontent.com/metal3-io/${repo}/${branch}/OWNERS_ALIASES" | \
            yq ".aliases.${maintainer_group}"
    done
}

echo "# All approvers from all top-level OWNERS files, including OWNERS_ALIASES"
echo "# Generated by community/maintainers/all-owners.sh"

# remove maintainers groups
for owner in "${OWNER_TYPES[@]}"; do
    echo -e "\n${owner}:"
    all_owners_raw "${owner}" | \
        grep -v -- "-maintainers" | \
        grep -v "null" | \
        grep -v "\.\.\." | \
        sort -uf
done
